### ISSUE TITLE
getT() in next13's generateMetadata() doesn't output any translations

### ISSUE THREAD

**Issue by synoptase** [aralroca/next-translate#1020]
**What version of this package are you using?**
`v2.0.5-canary.1`

**What operating system, Node.js, and npm version?**
macOS Ventura `13.2`, node `18.x`, yarn `3.5.0`

**What happened?**

Using `getT()` in a simple `generateMetadata` like below doesn't translate the key passed in the `t()` function.
```tsx
export async function generateMetadata() {
  const t = await getT('fr', 'common')

  return {
    title: t('title'),
    description: t('description'),
  }
}
```

Passing the `{ fallback: 'Super titre' }` option will show the fallback. It seems that the namespace isn't found.

**What did you expect to happen?**
Translated keys.

**Are you willing to submit a pull request to fix this bug?**

**Comment by kiyasov** [comment]
> **What version of this package are you using?** `v2.0.5-canary.1`
> 
> **What operating system, Node.js, and npm version?** macOS Ventura `13.2`, node `18.x`, yarn `3.5.0`
> 
> **What happened?**
> 
> Using `getT()` in a simple `generateMetadata` like below doesn't translate the key passed in the `t()` function.
> 
> ```tsx
> export async function generateMetadata() {
>   const t = await getT('fr', 'common')
> 
>   return {
>     title: t('title'),
>     description: t('description'),
>   }
> }
> ```
> 
> Passing the `{ fallback: 'Super titre' }` option will show the fallback. It seems that the namespace isn't found.
> 
> **What did you expect to happen?** Translated keys.
> 
> **Are you willing to submit a pull request to fix this bug?**

Hi! Did you find a solution?

**Comment by nkabour** [comment]
I'm having a similar problem; instead i get `t('title')` returns title and thats it. `props.params.lang` in the `generateMeta` props is not in sync with  `props.searchParams.lang`; where `props.params.lang`  is usually doesn't match the actual lang in the url.

**Comment by kiyasov** [comment]
> Hey; did you manage to find a solution for that? I'm having a similar problem; instead i get `t('title')` returns title and thats it. `props.params.lang` in the `generateMeta` props is not in sync with `props.searchParams.lang`; where `props.params.lang` is usually doesn't match the actual lang in the url.


Moved to https://next-intl-docs.vercel.app

**Comment by nkabour** [comment]
> > Hey; did you manage to find a solution for that? I'm having a similar problem; instead i get `t('title')` returns title and thats it. `props.params.lang` in the `generateMeta` props is not in sync with `props.searchParams.lang`; where `props.params.lang` is usually doesn't match the actual lang in the url.
> 
> Moved to https://next-intl-docs.vercel.app

i actually got it to work with `useTranslate` inside the generateMetaData; it works but i'm not sure if its ok to use the hook there; but as long it works ¯\_(ツ)_/¯; thanks for the reply 👍🏽

**Comment by aralroca** [comment]
It should work in 2.4.2 👌 I close the issue, feel free to comment and I will reopen the issue if doesn't work, but now getT is fixed to work in app dir

**Comment by aralroca** [comment]
BTW; probably you can use `useTranslation` hook, because in reality now is not a real hook and can be used as helper. Probably make sense to rename a copy of useTranslation as getTranslation to be consistent in the ecosystem semantics

**Comment by nkabour** [comment]
> BTW; probably you can use `useTranslation` hook, because in reality now is not a real hook and can be used as helper. Probably make sense to rename a copy of useTranslation as getTranslation to be consistent in the ecosystem semantics (this only applies in appDir, in pages folder is a real hook)

true thats what i've been doing so far; but it felt more like a workaround and sometimes title get stale and doesn't change during client nav. however it works well so far with v2.3.1. 

The new v2.4.4 still doesn't work for me but now i'm having the same behavior with the useTranslation hook in server components as well. This is the server component: 

```
import useTranslation from "next-translate/useTranslation"
import getT from "next-translate/getT"
import { Fragment } from "react"
import React from "react"
import { LoginFrom } from "../components/LoginForm"
import { GenerateMetadataProps } from "@/types/generate_metadata_props"

export default async function Login() {
  const { t } = useTranslation("login")
  console.log("this is login component: ", t("title"), t("description"))
  return (
    <Fragment>
      <div className="flex flex-col gap-y-2 pt-6  md:px-32 md:pt-32">
        <h3 className="text-2xl mt-2 text-white">{t("title")}</h3>
        <hr className="mt-2 mb-6" />
        <LoginFrom />
      </div>
    </Fragment>
  )
}

export async function generateMetadata({ params: { lang } }: GenerateMetadataProps) {
  const t = await getT(lang, "login")

  console.log("this is generate metadata: ", t("title"), t("description"))
  return {
    title: t("title"),
    description: t("description"),
  }
}
```

These are the logs from the server: 
```
next: next-translate - compiled page: /[lang]/(auth)/login - locale: en - namespaces: common, glossary, login - used loader: server /page
next: next-translate - compiled page: /[lang] - locale: en - namespaces: common, glossary - used loader: server /layout
next: this is generate metadata:  title description
next: this is login component:  title description
```

and here is my i18n.js: 

```
module.exports = {
  locales: ["en", "ar"],
  defaultLocale: "en",
  pages: {
    "*": ["common", "glossary"],
    "/[lang]/(auth)/login": ["login"],
  },
}

```

**Comment by aralroca** [comment]
@nkabour is working for you in 2.5.0-canary.3? thanks

**Comment by nkabour** [comment]
> @nkabour is working for you in 2.5.0-canary.3? thanks

with next-translate version `2.4.4` and next-translate-plugin version `2.5.0-canary.3`; it seems like server & client components translations are working as expected, but getT still gives the same results.  Here are the logs for server component and the getMetadata functions.

```
next: next-translate - compiled page: /[lang]/(auth)/login - locale: en - namespaces: common, glossary, login - used loader: server /page
next: next-translate - compiled page: /[lang] - locale: en - namespaces: common, glossary - used loader: server /layout
next: this is generate metadata title
next: this is server component Login
```

**Comment by wldhg** [comment]
still no translations returned in next-translate `2.5.3` with next-translate-plugin `2.5.3`

**Comment by sawa-ko** [comment]
Still not working @aralroca :(

**Comment by aralroca** [comment]
Should be fixed

**Comment by PierreNoll** [comment]
Hi there, maybe I'm missing something, but I think I still get the issue with `getT`, I created a [small repro on codesandbox](https://codesandbox.io/p/devbox/jdfxw9). The repro uses next-translate ^3.2.0, which should include the fix.

```js
// i18n.js
module.exports = {
  locales: ["en"],
  defaultLocale: "en",
  pages: {
    "/[lang]": ["home"], // app/page.tsx
  },
};
```

```tsx
// app/[lang]/page.tsx
import useTranslation from "next-translate/useTranslation";
import { Metadata } from "next";
import getT from "next-translate/getT";

type Props = { params: Promise<{ lang: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { lang } = await params;
  console.log("=====> lang is", lang);

  const tFromGetT = await getT(lang, "home");
  console.log("=====> getT title is", tFromGetT("title"));
  const { t } = useTranslation("home");
  console.log("=====> useTranslation title is", t("title"));
  return {
    title: t("title"),
  };
}
/** Add your relevant code here for the issue to reproduce */
export default function Home() {
  const { t } = useTranslation("home");
  return <div>hello {t("title")}</div>;
}
```

Produces the following logs (t from getT does not return the translated string)

```text
=====> lang is en
=====> getT title is title
=====> useTranslation title is Repro for getT in generateMetadata
```

I expect

```text
=====> lang is en
=====> getT title is Repro for getT in generateMetadata
=====> useTranslation title is Repro for getT in generateMetadata
```

Meanwhile I will use the useTranslation hook/helper as @aralroca said in https://github.com/aralroca/next-translate/issues/1020#issuecomment-1606201615 that works fine.

@aralroca Could you confirm whether getT is expected to work standalone in generateMetadata, or does it require something else like a custom loadLocaleFrom even when not using dynamicNamespace ?
