### ISSUE TITLE
Prop `placeholder` did not match.

### ISSUE THREAD

**Issue by william-fargues** [aralroca/next-translate#1066]
**What version of this package are you using?**
next-translate: 2.0.6
next-translate-plugin: 2.0.5

**What operating system, Node.js, and npm version?**
Windows 11 (wsl), Node 10.19.0, npm 6.14.4

**What happened?**
I'm working on a NextJS 13.4 project and the translations are working fine.

I have a `<CustomHeader />` component (Server component) in which I have an `<Autocomplete />` component (Client component).
Here's the code of the `<Autocomplete />`:
```
"use client"

import useTranslation from "next-translate/useTranslation"

export function Autocomplete() {
  const { t } = useTranslation("header")

  return (
      <input
        type="text"
        placeholder={t("search")}
      />
  )
```

The placeholder is translated correctly, but I get this error in the console: 
_Warning: Prop `placeholder` did not match. Server: "I'm the placeholder of the autocomplete" Client: "search"_

I understand that the key and the translated text are not matching between the server and the client but i don't know how to fix that.

**Comment by aralroca** [comment]
Can you try 2.3.0-canary.3 (next-translate and also next-translate-plugin), there are some improvements there because there are some breaking changes in Next.js 13.4

**Comment by aralroca** [comment]
Would be nice some feedback to know if this is already fixed in 2.3.0-canary.3 or not. Thanks!

**Comment by william-fargues** [comment]
Ok so I tried with the 2.3.0-canary.3 version for both next-translate and next-translate-plugin but I still have the error in the console :/

**Comment by aralroca** [comment]
Ok, good to know. Thanks. I'm going to investigate it. Can you provide me a repo with the reproduction of the error to be help us to reproduce it? Thanks

**Comment by william-fargues** [comment]
Here you are: [codesanbox](https://codesandbox.io/p/sandbox/wild-tree-594yhr?file=%2Fpackage.json%3A1%2C1)

Thank you

**Comment by aralroca** [comment]
Already fixed with:

- `next-translate` - version: [**`2.3.0-canary.3`**](https://github.com/aralroca/next-translate/releases/tag/2.3.0-canary.3)
- `next-translate-plugin` - version: [**`2.3.0-canary.5`**](https://github.com/aralroca/next-translate-plugin/releases/tag/2.3.0-canary.5)
